"""Handle enemies and arena fights."""
import random
import math

ENEMY_TYPES = [["Peasant"],
               ["Fighter",
                "Thief",
                "Apprentice"],
               ["Warrior",
                "Ranger",
                "Mage"],
               ["Paladin",
                "Assassin",
                "Wizard]"],
               ["Minotaur",
                "Ninja",
                "Archon"],
               ["Shadow"]]


def pick_diff(lvl):
    """Return a difficulty generated by user level."""
    range1 = enemy_range(1, lvl)
    range3 = range1 + enemy_range(3, lvl)
    range4 = range3 + enemy_range(4, lvl)
    range5 = range4 + enemy_range(5, lvl)
    range6 = range5 + enemy_range(6, lvl)
    pick = random.randint(1, 100)
    if pick < range1:
        difficulty = 1  # 1/10
    elif pick < range3:
        difficulty = 3  # 3/10
    elif pick < range4:
        difficulty = 4  # 4/10
    elif pick < range5:
        difficulty = 5  # 5/10
    elif pick < range6:
        difficulty = 6  # 10/10
    else:
        difficulty = 2  # 2/10
    return difficulty


def enemy_range(diff, lvl):
    """Return the available enemy range based on difficulty."""
    if diff == 1:
        if lvl < 90:
            return 90 - lvl
        else:
            return 0
    elif diff == 3:
        return lvl // 5 * 2
    elif diff == 4:
        if lvl > 25:
            return lvl // 5 * 2 - 10
        else:
            return 0
    elif diff == 5:
        if lvl > 40:
            return lvl // 5 * 2 - 20
        else:
            return 0
    elif diff == 6:
        if lvl > 75:
            return lvl / 5 * 2 - 30
        else:
            return 0


class Enemy(object):

    """Represent an enemy being fought."""

    def __init__(self, diff):
        super(Enemy, self).__init__()
        self.type = random.choice(ENEMY_TYPES[diff - 1])
        self.lvl = diff
        self.hp = diff * 250

    def damage_calc(self):
        """Return damage enemy deals."""
        base = self.lvl * 5
        rand = self.lvl * 2
        return random.randrange(base, base + rand)

    def damage_reduce(self, damage):
        """Return damage being dealt to enemy."""
        # TODO: agi = Dodge?
        return int(damage)

    def not_dead(self):
        """Return true if the enemy is still alive."""
        return self.hp > 0

    def calc_exp(self):
        """Calculate and return exp enemy produces."""
        # 2*I1^3 +3*I1^2 +I1 + 3
        i = self.lvl
        value = 2 * math.pow(i, 3) + 3 * math.pow(i, 2) + i + 3
        return int(value)

    def calc_gold(self):
        """Calculate and return gold enemy produces."""
        i = self.lvl
        value = 10 * math.pow(i, 2)
        return int(value)
